name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
    paths:
      - 'src/**' # Trigger only when code in src directory changes
      - 'public/**' # Trigger only when code in public directory changes
      - Dockerfile # Trigger only when Dockerfile changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username to secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password to secrets

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sololevelingquest/base-payload:latest
          platforms: linux/amd64
